version: "3"
volumes:
  bundle:       { driver: local }
  node_modules: { driver: local }
  config:       { driver: local }
  mahdi-qa-training-sync: { external: true }
services:
  app:
    # build allows using custom dockerfile while image is original version
    # build: .
    image: alpinelab/ruby-dev
    ports: ["5000:5000"]
    volumes:
      - mahdi-qa-training-sync:/app:nocopy
      - bundle:/bundle
      - node_modules:/app/node_modules
      - config:/config